# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20161025_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='book',
        ),
        migrations.AddField(
            model_name='checkout',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Branch'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
