# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20161027_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='book',
        ),
        migrations.AddField(
            model_name='return',
            name='checkouts',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='books.Checkout'),
        ),
        migrations.AlterField(
            model_name='return',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Branch'),
        ),
    ]
