# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20161028_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='book',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
