# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_return_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
